const sb=supabase.createClient('https://qgkrwfwhweqyzlzgwair.supabase.co','sb_publishable_caoCyu6MQc5R_-4t4qGE3A_z23R4rYh');
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
$$('.nav').forEach(b=>b.onclick=()=>{$$('.nav,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.view).classList.add('active');if(b.dataset.view==='games')loadGame()});
const val=(o,k)=>o[k]??''; const sum=(...n)=>n.every(x=>x!=null)?n.reduce((a,b)=>a+Number(b),0):'';
async function loadScores(){const {data,error}=await sb.from('league_scores').select('*').eq('season','2026 American').order('week');if(error)return console.error(error);let runningGames=0,runningPins=0;$('#scoresBody').innerHTML=data.map(r=>{const series=sum(r.game1,r.game2,r.game3);if(series!==''){runningPins+=series;runningGames+=3}const newAvg=runningGames?Math.floor(runningPins/runningGames):'';return `<tr><td><b>${r.week}</b></td><td>${val(r,'starting_avg')}</td><td class="${r.game1>=290?'hot':''}">${val(r,'game1')}</td><td class="${r.game2>=290?'hot':''}">${val(r,'game2')}</td><td class="${r.game3>=290?'hot':''}">${val(r,'game3')}</td><td class="series">${series}</td><td class="hot">${r.points_won}</td><td>${newAvg}</td><td>${val(r,'opponent_avg')}</td><td>${val(r,'opponent_game1')}</td><td>${val(r,'opponent_game2')}</td><td>${val(r,'opponent_game3')}</td><td>${sum(r.opponent_game1,r.opponent_game2,r.opponent_game3)}</td><td><button onclick="editWeek(${r.week})">Edit</button></td></tr>`}).join('');$('#wins').textContent=data.reduce((a,r)=>a+(r.points_won||0),0)}
$('#addWeek').onclick=()=>{$('#scoreForm').reset();$('#scoreDialog').showModal()};$('#cancelScore').onclick=()=>$('#scoreDialog').close();
window.editWeek=async w=>{const {data}=await sb.from('league_scores').select('*').eq('season','2026 American').eq('week',w).single();Object.entries(data||{}).forEach(([k,v])=>{if($('#scoreForm').elements[k])$('#scoreForm').elements[k].value=v??''});$('#scoreDialog').showModal()};
$('#scoreForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target), row={season:'2026 American'};for(const [k,v] of f)row[k]=v===''?null:Number(v);const {error}=await sb.from('league_scores').upsert(row,{onConflict:'season,week'});if(error)return alert(error.message);$('#scoreDialog').close();loadScores()};
let players=[];async function loadGame(){const week=Number($('#gameWeek').value)||1;let {data:p}=await sb.from('card_game_players').select('*').eq('active',true).order('display_order');players=p||[];let {data:n}=await sb.from('card_game_nights').select('*').eq('season','2026 American').eq('week',week).maybeSingle();if(!n){const res=await sb.from('card_game_nights').insert({season:'2026 American',week}).select().single();n=res.data}const {data:stats}=await sb.from('card_game_stats').select('*').eq('night_id',n.id);const map=Object.fromEntries((stats||[]).map(s=>[s.player_id,s]));$('#players').innerHTML=players.map(p=>card(p,map[p.id]||{assassinations:0,self_inflictions:0,whammies:0,games_won:0},n.id)).join('');loadLeaders()}
function card(p,s,nid){return `<div class="player-card"><h3>${p.name}</h3>${stat('Assassinations','assassinations',s.assassinations,p.id,nid)}${stat('Self Inflictions','self_inflictions',s.self_inflictions,p.id,nid)}${stat('Games Won','games_won',s.games_won,p.id,nid)}${stat('WHAMMIES!','whammies',s.whammies,p.id,nid,true)}</div>`}
function stat(label,key,num,pid,nid,w=false){return `<div class="stat"><span>${label}</span><strong>${num}</strong><button class="mini ${w?'whammy-btn':''}" onclick="bump(${pid},'${key}',${nid},${num})">+1</button></div>`}
window.bump=async(pid,key,nid,current)=>{const row={night_id:nid,player_id:pid,[key]:current+1};const {data:old}=await sb.from('card_game_stats').select('*').eq('night_id',nid).eq('player_id',pid).maybeSingle();if(old)Object.assign(row,old,{[key]:current+1});const {error}=await sb.from('card_game_stats').upsert(row,{onConflict:'night_id,player_id'});if(error)alert(error.message);else loadGame()};
async function loadLeaders(){const {data}=await sb.from('card_game_stats').select('player_id,assassinations,self_inflictions,whammies,games_won');const totals={};(data||[]).forEach(s=>{totals[s.player_id]??={assassinations:0,self_inflictions:0,whammies:0,games_won:0};Object.keys(totals[s.player_id]).forEach(k=>totals[s.player_id][k]+=s[k])});const cats=[['assassinations','Deadliest Assassin'],['self_inflictions','Most Suicidal'],['whammies','Whammy King'],['games_won','Games Won']];$('#leaders').innerHTML=cats.map(([k,label])=>{let best=players.map(p=>[p.name,totals[p.id]?.[k]||0]).sort((a,b)=>b[1]-a[1])[0]||['—',0];return `<div class="leader"><b>${best[0]} · ${best[1]}</b><span>${label}</span></div>`}).join('')}
$('#loadGame').onclick=loadGame;loadScores();