const sb=supabase.createClient('https://qgkrwfwhweqyzlzgwair.supabase.co','sb_publishable_caoCyu6MQc5R_-4t4qGE3A_z23R4rYh');
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);let scores=[],players=[],nightId=null,currentWeek=1,scoreWeek=1;
const num=v=>v===''||v==null?null:Number(v), handicap=a=>a==null?0:Math.max(0,Math.floor((230-a)*.9));
$$('.nav').forEach(b=>b.onclick=()=>{$$('.nav,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.view).classList.add('active');if(b.dataset.view!=='scores')loadGame()});
async function loadScores(){const {data,error}=await sb.from('league_scores').select('*').eq('season','2026 American').order('week');if(error)return alert(error.message);scores=data||[];renderScoreWeek();$('#wins').textContent=scores.reduce((a,r)=>a+calcPoints(r),0)}
function blankWeek(w){return {season:'2026 American',week:w,starting_avg:null,game1:null,game2:null,game3:null,opponent_avg:null,opponent_game1:null,opponent_game2:null,opponent_game3:null}}
function scoreRow(){return scores.find(r=>r.week===scoreWeek)||blankWeek(scoreWeek)}
function gameResult(r,i){const m=[r.game1,r.game2,r.game3][i],o=[r.opponent_game1,r.opponent_game2,r.opponent_game3][i];if(m==null||o==null)return '';const mh=handicap(r.starting_avg),oh=handicap(r.opponent_avg);return m+mh>o+oh?'W':m+mh<o+oh?'L':'T'}
function calcPoints(r){return [0,1,2].filter(i=>gameResult(r,i)==='W').length}
function runningAverage(through){let pins=0,games=0;scores.filter(x=>x.week<=through).sort((a,b)=>a.week-b.week).forEach(r=>[r.game1,r.game2,r.game3].forEach(v=>{if(v!=null){pins+=Number(v);games++}}));return games?Math.floor(pins/games):''}
function box(label,key,value,result=''){return `<label class="score-box ${result==='W'?'won':result==='L'?'lost':''}"><span>${label}</span><input data-key="${key}" type="number" min="0" max="300" inputmode="numeric" value="${value??''}" placeholder="—"></label>`}
function renderScoreWeek(){const r=scoreRow(),mine=[r.game1,r.game2,r.game3],opp=[r.opponent_game1,r.opponent_game2,r.opponent_game3],mySeries=mine.every(v=>v!=null)?mine.reduce((a,b)=>a+Number(b),0):'—',oppSeries=opp.every(v=>v!=null)?opp.reduce((a,b)=>a+Number(b),0):'—',newAvg=runningAverage(scoreWeek)||'—';$('#currentWeekLabel').textContent=scoreWeek;$('#prevWeek').disabled=scoreWeek<=1;$('#scoreBoard').innerHTML=`<div class="bowler-block"><div class="bowler-title"><div><span>YOU</span><strong>My Scores</strong></div>${box('AVG','starting_avg',r.starting_avg)}</div><div class="game-boxes">${mine.map((v,i)=>box(`GAME ${i+1}`,`game${i+1}`,v,gameResult(r,i))).join('')}<div class="calc-box"><span>SERIES</span><strong>${mySeries}</strong></div></div></div><div class="match-summary"><div><span>Handicap</span><strong>${handicap(r.starting_avg)} - ${handicap(r.opponent_avg)}</strong></div><div><span>Points Won</span><strong>${calcPoints(r)}</strong></div><div><span>New Average</span><strong>${newAvg}</strong></div></div><div class="bowler-block opponent-block"><div class="bowler-title"><div><span>OPPONENT</span><strong>Opponent Scores</strong></div>${box('AVG','opponent_avg',r.opponent_avg)}</div><div class="game-boxes">${opp.map((v,i)=>box(`GAME ${i+1}`,`opponent_game${i+1}`,v)).join('')}<div class="calc-box"><span>SERIES</span><strong>${oppSeries}</strong></div></div></div><div id="saveState" class="save-state">Tap a box and enter a score — changes save automatically.</div>`;$$('#scoreBoard input').forEach(i=>{i.onchange=()=>saveScore(i.dataset.key,i.value);i.onfocus=e=>e.target.select()})}
async function saveScore(key,value){const existing=scoreRow(),row={...blankWeek(scoreWeek),...existing,[key]:num(value)};row.points_won=calcPoints(row);delete row.id;delete row.created_at;delete row.updated_at;const state=$('#saveState');if(state)state.textContent='Saving…';const {error}=await sb.from('league_scores').upsert(row,{onConflict:'season,week'});if(error){if(state)state.textContent='Could not save';return alert(error.message)}await loadScores();const s=$('#saveState');if(s)s.textContent='Saved ✓'}
$('#prevWeek').onclick=()=>{if(scoreWeek>1){scoreWeek--;renderScoreWeek()}};$('#nextWeek').onclick=()=>{scoreWeek++;renderScoreWeek()};$('#addWeek').onclick=()=>{scoreWeek=scores.length?Math.max(...scores.map(r=>r.week))+1:1;renderScoreWeek()};$('#deleteWeek').onclick=async()=>{const exists=scores.some(r=>r.week===scoreWeek);if(!exists)return;if(!confirm(`Delete Week ${scoreWeek}?`))return;const {error}=await sb.from('league_scores').delete().eq('season','2026 American').eq('week',scoreWeek);if(error)return alert(error.message);await loadScores();scoreWeek=Math.max(1,Math.min(scoreWeek,scores.length?Math.max(...scores.map(r=>r.week)):1));renderScoreWeek()};
$$('.loadGame').forEach(b=>b.onclick=()=>{currentWeek=Number(b.parentElement.querySelector('.gameWeek').value)||1;$$('.gameWeek').forEach(i=>i.value=currentWeek);loadGame()});
async function loadGame(){currentWeek=Number($('.view.active .gameWeek')?.value)||currentWeek||1;$$('.gameWeek').forEach(i=>i.value=currentWeek);let {data:p}=await sb.from('card_game_players').select('*').eq('active',true).order('display_order');players=p||[];let {data:n}=await sb.from('card_game_nights').select('*').eq('season','2026 American').eq('week',currentWeek).maybeSingle();if(!n){const res=await sb.from('card_game_nights').insert({season:'2026 American',week:currentWeek}).select().single();n=res.data}nightId=n.id;const {data:s}=await sb.from('card_game_stats').select('*').eq('night_id',nightId);const map=Object.fromEntries((s||[]).map(x=>[x.player_id,x]));renderKill(map);renderCounters(map);drawWinsChart()}
function renderKill(map){const el=$('#killChamber');if(!el)return;el.innerHTML=`<div class="chamber-center"><div class="cylinder">${[0,1,2,3,4,5].map(i=>'<i></i>').join('')}</div><b>KILL<br>CARDS</b></div>`+players.map((p,i)=>{const s=map[p.id]||{};return `<div class="chamber-player p${i}"><h3>${p.name}</h3>${counter('Assassinations','assassinations',s.assassinations||0,p.id)}${counter('Self Inflictions','self_inflictions',s.self_inflictions||0,p.id)}</div>`}).join('')}
function renderCounters(map){$('#winsButtons').innerHTML=players.map(p=>bigCounter(p,'games_won',map[p.id]?.games_won||0,'+ WIN')).join('');$('#whammyButtons').innerHTML=players.map(p=>bigCounter(p,'whammies',map[p.id]?.whammies||0,'WHAMMY!','whammy-counter')).join('')}
function counter(label,key,v,pid){return `<div class="small-counter"><span>${label}</span><strong>${v}</strong><button onclick="bump(${pid},'${key}',${v})">+1</button></div>`}function bigCounter(p,key,v,label,cls=''){return `<div class="big-counter ${cls}"><h3>${p.name}</h3><strong>${v}</strong><button onclick="bump(${p.id},'${key}',${v})">${label}</button></div>`}
window.bump=async(pid,key,current)=>{const {data:old}=await sb.from('card_game_stats').select('*').eq('night_id',nightId).eq('player_id',pid).maybeSingle();const row=old?{...old,[key]:current+1}:{night_id:nightId,player_id:pid,[key]:current+1};const {error}=await sb.from('card_game_stats').upsert(row,{onConflict:'night_id,player_id'});if(error)return alert(error.message);loadGame()};
async function drawWinsChart(){const canvas=$('#winsChart');if(!canvas)return;const {data}=await sb.from('card_game_stats').select('player_id,games_won,card_game_nights!inner(week,season)').eq('card_game_nights.season','2026 American');const by={};players.forEach(p=>by[p.id]={name:p.name,vals:{}});(data||[]).forEach(x=>{if(by[x.player_id])by[x.player_id].vals[x.card_game_nights.week]=(by[x.player_id].vals[x.card_game_nights.week]||0)+(x.games_won||0)});const weeks=[...new Set((data||[]).map(x=>x.card_game_nights.week))].sort((a,b)=>a-b);const ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);ctx.strokeStyle='#3b4352';ctx.fillStyle='#9da8ba';ctx.font='14px system-ui';for(let y=40;y<h-45;y+=60){ctx.beginPath();ctx.moveTo(55,y);ctx.lineTo(w-25,y);ctx.stroke()}const colors=['#ffc928','#4e8cff','#ef3f47','#62d49b','#c58cff','#ff8f45'];Object.values(by).forEach((p,pi)=>{let total=0;ctx.strokeStyle=colors[pi%colors.length];ctx.lineWidth=4;ctx.beginPath();weeks.forEach((wk,i)=>{total+=p.vals[wk]||0;const x=70+(weeks.length<=1?0:i*(w-120)/(weeks.length-1)),y=h-60-total*32;i?ctx.lineTo(x,y):ctx.moveTo(x,y);ctx.fillStyle=colors[pi%colors.length];ctx.fillText(p.name,70+pi*130,22)});ctx.stroke()});weeks.forEach((wk,i)=>{const x=70+(weeks.length<=1?0:i*(w-120)/(weeks.length-1));ctx.fillStyle='#9da8ba';ctx.fillText(`W${wk}`,x-8,h-25)})}
loadScores();