const sb=supabase.createClient('https://qgkrwfwhweqyzlzgwair.supabase.co','sb_publishable_caoCyu6MQc5R_-4t4qGE3A_z23R4rYh');
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);let scores=[],players=[],nightId=null,currentWeek=1,openWeek=null,initialScoresLoaded=false;
const num=v=>v===''||v==null?null:Number(v), handicap=a=>a==null?0:Math.max(0,Math.floor((230-a)*.9));
$$('.nav').forEach(b=>b.onclick=()=>{$$('.nav,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.view).classList.add('active');if(b.dataset.view==='kill')loadGame()});
function blankWeek(w){return {season:'2026 American',week:w,starting_avg:null,game1:null,game2:null,game3:null,opponent_avg:null,opponent_game1:null,opponent_game2:null,opponent_game3:null}}
function gameResult(r,i){const m=[r.game1,r.game2,r.game3][i],o=[r.opponent_game1,r.opponent_game2,r.opponent_game3][i];if(m==null||o==null)return '';return m+handicap(r.starting_avg)>o+handicap(r.opponent_avg)?'W':m+handicap(r.starting_avg)<o+handicap(r.opponent_avg)?'L':'T'}
function calcPoints(r){return [0,1,2].reduce((points,i)=>points+(gameResult(r,i)==='W'?1:gameResult(r,i)==='T'?.5:0),0)}
function series(r,p=''){const a=[r[p+'game1'],r[p+'game2'],r[p+'game3']];return a.every(v=>v!=null)?a.reduce((x,y)=>x+Number(y),0):''}
function runningAverage(through){let pins=0,games=0;scores.filter(x=>x.week<=through).sort((a,b)=>a.week-b.week).forEach(r=>[r.game1,r.game2,r.game3].forEach(v=>{if(v!=null){pins+=Number(v);games++}}));return games?Math.round(pins/games):''}
async function loadScores(){const {data,error}=await sb.from('league_scores').select('*').eq('season','2026 American').order('week');if(error)return alert(error.message);scores=data||[];if(!scores.some(r=>r.week===1))scores.unshift(blankWeek(1));if(!initialScoresLoaded){openWeek=Math.max(...scores.map(r=>Number(r.week)||1));initialScoresLoaded=true}renderWeeks();$('#wins').textContent=scores.reduce((a,r)=>a+calcPoints(r),0)}
function inputBox(label,key,val,w,result=''){return `<label class="entry-box ${result==='W'?'won':result==='L'?'lost':''}"><span>${label}</span><input type="number" min="0" max="300" inputmode="numeric" data-week="${w}" data-key="${key}" value="${val??''}" placeholder="—"></label>`}
function renderWeeks(){const list=[...scores].sort((a,b)=>a.week-b.week);$('#weeksList').innerHTML=list.map(r=>{const total=series(r),newAvg=runningAverage(r.week),expanded=r.week===openWeek;return `<article class="week-card ${expanded?'expanded':''}" data-week="${r.week}"><button class="week-summary" onclick="toggleWeek(${r.week})"><strong>Week ${r.week}</strong><span>Avg: <b>${r.starting_avg??'—'}</b></span><span class="summary-highlight">Total Pins: <b>${total||'—'}</b></span><span class="summary-highlight">Points Won: <b>${calcPoints(r)}</b></span><span>New Avg: <b>${newAvg||'—'}</b></span><i>${expanded?'▲':'▼'}</i></button><div class="week-details"><div class="score-grid header"><span>My AVG</span><span>Game 1</span><span>Game 2</span><span>Game 3</span><span>Total</span></div><div class="score-grid">${inputBox('My AVG','starting_avg',r.starting_avg,r.week)}${[0,1,2].map(i=>inputBox(`Game ${i+1}`,`game${i+1}`,r[`game${i+1}`],r.week,gameResult(r,i))).join('')}<div class="total-box"><strong>${total||'—'}</strong></div></div><div class="score-grid header opp-head"><span>Opp Avg</span><span>Game 1</span><span>Game 2</span><span>Game 3</span><span>Total</span></div><div class="score-grid">${inputBox('Opp Avg','opponent_avg',r.opponent_avg,r.week)}${[1,2,3].map(i=>inputBox(`Game ${i}`,`opponent_game${i}`,r[`opponent_game${i}`],r.week)).join('')}<div class="total-box"><strong>${series(r,'opponent_')||'—'}</strong></div></div><div class="detail-footer"><span>Handicap: You ${handicap(r.starting_avg)} · Opp ${handicap(r.opponent_avg)}</span><span class="save-note">Changes save automatically</span>${r.week>1?`<button type="button" class="danger small-delete" data-delete-week="${r.week}">Delete Week</button>`:''}</div></div></article>`}).join('');$$('#weeksList input').forEach(i=>{i.onfocus=e=>e.target.select();i.onchange=()=>saveScore(Number(i.dataset.week),i.dataset.key,i.value)});$$('[data-delete-week]').forEach(b=>b.onclick=e=>removeWeek(e,Number(b.dataset.deleteWeek)))}
window.toggleWeek=w=>{openWeek=openWeek===w?null:w;renderWeeks()};
async function saveScore(w,key,value){let old=scores.find(r=>r.week===w)||blankWeek(w),row={...blankWeek(w),...old,[key]:num(value)};row.points_won=calcPoints(row);['id','created_at','updated_at'].forEach(k=>delete row[k]);const {error}=await sb.from('league_scores').upsert(row,{onConflict:'season,week'});if(error)return alert(error.message);openWeek=w;await loadScores()}
$('#addWeek').onclick=()=>{const max=scores.length?Math.max(...scores.map(r=>r.week)):0,w=max+1;scores.push(blankWeek(w));openWeek=w;renderWeeks()};
async function removeWeek(e,w){e.preventDefault();e.stopPropagation();if(w===1)return;if(!confirm(`Delete Week ${w}?`))return;const saved=scores.find(r=>r.week===w)?.id;if(saved){const {error}=await sb.from('league_scores').delete().eq('season','2026 American').eq('week',w);if(error)return alert(error.message)}scores=scores.filter(r=>r.week!==w);openWeek=scores.length?Math.max(...scores.map(r=>Number(r.week)||1)):1;await loadScores()}
$$('.loadGame').forEach(b=>b.onclick=()=>{currentWeek=Number(b.parentElement.querySelector('.gameWeek').value)||1;$$('.gameWeek').forEach(i=>i.value=currentWeek);loadGame()});
async function loadGame(){currentWeek=Number($('.view.active .gameWeek')?.value)||currentWeek||1;$$('.gameWeek').forEach(i=>i.value=currentWeek);let {data:p}=await sb.from('card_game_players').select('*').eq('active',true).order('display_order');players=p||[];let {data:n}=await sb.from('card_game_nights').select('*').eq('season','2026 American').eq('week',currentWeek).maybeSingle();if(!n){const res=await sb.from('card_game_nights').insert({season:'2026 American',week:currentWeek}).select().single();n=res.data}nightId=n.id;const {data:s}=await sb.from('card_game_stats').select('*').eq('night_id',nightId);const map=Object.fromEntries((s||[]).map(x=>[x.player_id,x]));renderKill(map)}
const killCards={Chris:{rank:'3',suit:'♥',red:true},Scott:{rank:'4',suit:'♠'},Dave:{rank:'4',suit:'♥',red:true},Brandon:{rank:'2',suit:'♣'},Chad:{rank:'2',suit:'♠'}};
function playerCard(name){const c=killCards[name];return c?`<span class="player-card ${c.red?'red-card':'black-card'}" aria-label="${c.rank} ${c.suit}"><b>${c.rank}</b><i>${c.suit}</i></span>`:''}
function renderKill(map){const el=$('#killChamber');if(!el)return;el.innerHTML=`<div class="chamber-center"><div class="cylinder">${[0,1,2,3,4,5].map(i=>'<i></i>').join('')}</div><b>KILL<br>CARDS</b></div>`+players.map((p,i)=>{const s=map[p.id]||{};return `<div class="chamber-player p${i}"><div class="player-heading"><h3>${p.name}</h3>${playerCard(p.name)}</div>${counter('Assassinations','assassinations',s.assassinations||0,p.id)}${counter('Self Inflictions','self_inflictions',s.self_inflictions||0,p.id)}</div>`}).join('')}
function counter(label,key,v,pid){return `<div class="small-counter"><span>${label}</span><strong>${v}</strong><button onclick="bump(${pid},'${key}',${v})">+1</button></div>`}
window.bump=async(pid,key,current)=>{const {data:old}=await sb.from('card_game_stats').select('*').eq('night_id',nightId).eq('player_id',pid).maybeSingle();const row=old?{...old,[key]:current+1}:{night_id:nightId,player_id:pid,[key]:current+1};const {error}=await sb.from('card_game_stats').upsert(row,{onConflict:'night_id,player_id'});if(error)return alert(error.message);loadGame()};
loadScores();